### ISSUE TITLE
the messages creator needs optimization !   

### ISSUE THREAD

**Issue by minanagehsalalma** [t0xic-m/instagram_json_viewer#1]
![image](https://user-images.githubusercontent.com/20546638/56050995-a1354a80-5d4d-11e9-824c-4f67a6e4acfe.png)

like making a new pdf file for every chat

and sort the messages from the newest to the oldest just like what the app does ..

and i don't think the images viewing system works as instagram made a lot of updates

**Comment by t0xic-m** [comment]
should be fixed

**Comment by minanagehsalalma** [comment]
> should be fixed
@t0xic-m can we get an image of it working ? I CAN'T check it this while ;(

**Comment by t0xic-m** [comment]
of course, here are 2 screenshots:
https://t0xic-m.github.io/instagram_json_viewer/screenshot1.jpg
https://t0xic-m.github.io/instagram_json_viewer/screenshot2.jpg
and a youtube video:
https://www.youtube.com/watch?v=0CUbTkrK62M

**Comment by minanagehsalalma** [comment]
@t0xic-m hi great and all but why it's not clear ?
For messages it should be something like this
https://github.com/igdmapps/igdm

And i think every profile should have a different html file that contains everything about them.

Or every profile have a folder with html files of story and messages..etc

**Comment by t0xic-m** [comment]
The messages section is basically the same as in the repo you linked. Just with more fancy design!
And there's not need for different profiles because when you download your data from instagram you only get your own profile!
Don't forget that this is not an instagram client, this is just an html interface that shows the json content in a human readable way!
But feel free to extend the python code to your own needs!

**Comment by minanagehsalalma** [comment]
@t0xic-m 
"download your data from instagram you only get your own profile!"

I meant the people  i am messaging. ..

And isn't that all too much for a one html file  ? Won't the browser crash and also using find takes forever and the browser becomes freezed.

**Comment by t0xic-m** [comment]
Of course you could download every profile from the people you are messaging, but that's not what my goal was with this repo. But it is like 2 lines of python code to add if you want to do that, however I am pretty sure that instagram will deny your requests if you have to many conversations!

That's why every chat is in a separate html file, otherwise yes, your browser would probably crash!

**Comment by minanagehsalalma** [comment]
> Of course you could download every profile from the people you are messaging, 

Mattte i mean the chat thread of them not their profiles !

"That's why every chat is in a separate html file," 

Is it ? This not what  i saw in the vid !

**Comment by t0xic-m** [comment]
Maybe try running it first before you get more confused just by screenshots and a video ;)
