### ISSUE TITLE
WinError 3 regarding progile picture

### ISSUE THREAD

**Issue by raymonders** [t0xic-m/instagram_json_viewer#2]
[WinError 3] The system cannot find the path specified: 'profile'
ERROR fetching profile picture locally!
Trying to fetch online...
WARNING - error getting avatar for user anna.b.braga!
HTTP Error 404: Not Found

im getting this message when running the windows exe file, and i dont understand how to fix it. can you help?

**Comment by t0xic-m** [comment]
So these are actually two different errors:
- The first is that your own profile picture couldn't be found in your instagram data. It fetches the profile picture online therefore!
- The second error is either because the account doesn't exist anymore or because instagram timed out your requests!
In both cases you don't have to do anything, as the program has a fallback option in those cases. You should still get the html file produced normally!
If that is not the case - please let me know!
